apiVersion: v1
kind: PersistentVolume
metadata:
  name: dapr-scheduler-data-dir-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/dapr-scheduler-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dapr-scheduler-data-dir-dapr-scheduler-server-0
  namespace: dapr-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: dapr-scheduler-data-dir-pv

